spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=scanner;trustServerCertificate=true
    username: SA
    password: P@ssw0rd
  jpa:
#    show-sql: true
    properties:
      hibernate:
        jdbc:
          fetch_size: 100
#        generate_statistics: true
        order_inserts: true
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: create_daily_data.sql
              create-source: metadata

twelve-data:
  base-url: https://api.twelvedata.com
  request-rate: 2.4 # Per second

y-finance:
  request-rate: 2 # Per second