spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=scanner;trustServerCertificate=true
    username: SA
    password: P@ssw0rd
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: create_daily_data.sql
              create-source: metadata

twelve-data:
  base-url: https://api.twelvedata.com
  request-rate: 0.9 # Per second